# Site settings
email: janemon2331@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page:num"
google_analytics: 

# SEO settings
title: Janemon's Blog 
description: programming 
url: "www.yewfyewq.com"
twitter_username: 
default_img:  

# Profile settings
name: Janemon 
profile_img: _screenshots/screenshot-1.png
profile: "那天,那个人说了一句话:' Joy maybe end in Grief.'" 
social:
  email: janemon2331@gmail.com
  github: https://github.com/Janemon 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
